"""KM governance vocabulary URIs (spec §6.1)."""

KM = "http://km.local/governance#"
KM_LOCAL_EXCEPTION = f"{KM}LocalException"
KM_BYPASSES_SHAPE = f"{KM}bypassesShape"
KM_TARGET_NODE = f"{KM}targetNode"
KM_RATIONALE = f"{KM}rationale"
KM_STATUS = f"{KM}status"
KM_APPROVED_BY = f"{KM}approvedBy"
KM_SIGNATURE = f"{KM}signature"
KM_TIMESTAMP = f"{KM}timestamp"

KM_SEMANTIC_MERGE_REQUEST = f"{KM}SemanticMergeRequest"
KM_TARGET_ONTOLOGY = f"{KM}targetOntology"
KM_PROPOSAL_GRAPH = f"{KM}proposalGraph"
KM_AUTHOR = f"{KM}author"
KM_CREATED_AT = f"{KM}createdAt"
KM_REVIEW_DOC = f"{KM}reviewDoc"
KM_DIFF_DELETIONS = f"{KM}diffDeletions"
KM_APPROVER = f"{KM}approver"
KM_APPROVED_AT = f"{KM}approvedAt"
KM_REJECTOR = f"{KM}rejector"
KM_REJECTED_AT = f"{KM}rejectedAt"

KM_BRANCH_MERGE_RESOLUTION = f"{KM}BranchMergeResolution"
KM_SOURCE_GRAPH = f"{KM}sourceGraph"
KM_TARGET_GRAPH = f"{KM}targetGraph"
KM_RESOLUTION = f"{KM}resolution"
KM_POLICY = f"{KM}policy"
KM_EXCEPTIONS_COPIED = f"{KM}exceptionsCopied"
KM_TRIPLES_IMPORTED = f"{KM}triplesImported"
KM_RECORDED_AT = f"{KM}recordedAt"
KM_DELETE_SUBJECT = f"{KM}deleteSubject"

CASE_GOVERNANCE_GRAPH = "http://km.local/case/governance"

STATUS_PENDING = "PENDING_APPROVAL"
STATUS_APPROVED = "APPROVED"
STATUS_REJECTED = "REJECTED"

EXCEPTION_BASE = "http://km.local/exceptions/"
